/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StakeImport } from './routes/stake'
import { Route as JoinImport } from './routes/join'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StakeRoute = StakeImport.update({
  path: '/stake',
  getParentRoute: () => rootRoute,
} as any)

const JoinRoute = JoinImport.update({
  path: '/join',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinImport
      parentRoute: typeof rootRoute
    }
    '/stake': {
      id: '/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof StakeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/stake': typeof StakeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/stake': typeof StakeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/stake': typeof StakeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/join' | '/stake'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/join' | '/stake'
  id: '__root__' | '/' | '/join' | '/stake'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  StakeRoute: typeof StakeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  StakeRoute: StakeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/join",
        "/stake"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/join": {
      "filePath": "join.tsx"
    },
    "/stake": {
      "filePath": "stake.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
